name: 'Flame Dartdoc'
description: 'An opinionated action that validates a Flutter project Dartdoc'
author: 'flame-engine'

branding:
  color: red
  icon: code

runs:
  using: 'bash'
  main: scripts/dartdoc.sh
